services:
  accountservice:
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    ports:
    - '80:8080'
    depends_on:
    - keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
        - KC_HEALTH_ENABLED=true
        - KEYCLOAK_ADMIN=${KC_ADMIN_LOGIN}
        - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    volumes:
    - ././containers/identity:/opt/keycloak/data
    ports:
    - '18000:8080'
  postgressql:
    container_name: postgres
    image: postgres:16.2
    environment:
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=account_base'
    volumes:
     - postgres_data:/var/lib/postgresql/data
    ports:
    - '5432:5432'